APP/Areas/Main/Controllers/CityController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Models;
using Models.Enum;
using Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Utility;

namespace APP.Areas.Main.Controllers
{

    [Area("Main")]
    [Authorize(Roles = SD.RoleAdmin)]
    public class CityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<AircraftController> _logger;
        public readonly IWebHostEnvironment _hostEnvironment;
        public CityController(ILogger<AircraftController> logger, IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            City city = new City();
            if (id == null)
            {
                //this is for create
              
                return View(city);
            }
            //this is for edit
            city = await _unitOfWork.city.GetAsync(id.GetValueOrDefault());

            if (city == null)
            {
                return NotFound();
            }
            return View(city);

        }       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(City city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (city.Id == 0)
                    {
                        await _unitOfWork.city.AddAsync(city);
                    }
                    else
                    {
                        var obj = await _unitOfWork.city.GetFirstOrDefaultAsync(a => a.Id == city.Id);
                        _unitOfWork.city.Update(city);
                    }
                    _unitOfWork.SaveAsync();
                    //TempData["AlertMsg"] = "Record Created Sucessfully...!";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ex.Message.ToString();
                    throw;
                }
                
            }
            return View(city);
        }

        #region Data Loads
        [HttpGet]
        public async Task<IActionResult> GetAllCity()
        {
            var objList = await _unitOfWork.city.GetAllAsync();                      
                          
            return Json(new { data = objList });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var objFromDb = await _unitOfWork.city.GetAsync(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.city.Remove(objFromDb);
            _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion

    }
}

APP/Areas/Main/Views/City/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="card card-light">
        <div class="card-header">
            <h3 class="card-title font-weight-bold">Country Information</h3>
            <div class="card-tools">
                <a class="btn-sm btn-info text-white" asp-area="Main" asp-controller="City" asp-action="Upsert">
                    Create New Country
                </a>
            </div>
        </div>
        <div class="card-body">
            <table id="tblData" class="table table-bordered table-hover" style="width:100%;">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>                      
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
            </table>

        </div>
    </div>
</div>

@section Styles{
    <link rel="stylesheet" href="~/css/bundles/dataTables.min.css">
    <link rel="stylesheet" href="~/css/bundles/sweetalert2.min.css">
    <link rel="stylesheet" href="~/css/bundles/toastr.min.css">
}
@section Scripts{
    <script src="~/js/bundles/dataTables.min.js"></script>
    <script src="~/js/bundles/sweetalert2.min.js"></script>
    <script src="~/js/bundles/toastr.min.js"></script>
    <script src="~/js/custom/city/city.js"></script>
}

APP/Areas/Main/Views/City/Upsert.cshtml
@using System.Text.Json;
@using Utility;
@model Models.City
@using Models.Enum;
@{
    ViewData["Title"] = "Upsert";
    string title = "Create Country ";
}

<style>
    .select2-container--default .select2-selection--multiple .select2-selection__choice {
        color: black;
    }

    .required:after {
        content: " *";
        color: red;
    }
</style>
<div class="container">
    <div class="card">
        <div class="card-header bg-gradient-lightblue">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (Model.Id != 0)
            {
                //edit
                title = "Edit Country";
            }
            <h3 class="card-title" style="font-weight:bold">@title</h3>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                @*<div asp-validation-summary="All" class="text-danger"></div>*@

                <div class="form-group row">
                    <div class="col-md-4">
                        <label class="required" asp-for="Name"></label>
                    </div>
                    <div class="col-md-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-8 offset-md-4">
                        <div class="row">
                            @if (Model.Id != 0)
                            {
                                <div class="col">
                                    <button type="submit" id="btnUpdate" class="btn btn-warning form-control" asp-route-id="@Model.Id">Update</button>
                                </div>
                            }
                            else
                            {
                                <div class="col">
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                </div>
                            }

                            <div class="col">
                                <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>